### ISSUE TITLE
issue opening 

### ISSUE THREAD

**Issue by ghost** [patrickshox/Simplifier-for-Facebook#3]
<img width="502" alt="Screenshot 2021-02-13 at 09 36 15" src="https://user-images.githubusercontent.com/79003022/107846936-a945f180-6ddf-11eb-8569-2a515e9ff58b.png">

Recieving this message when trying to use, any help please

**Comment by patrickshox** [comment]
Safari Content Blockers don't get permissions to read/transmit data. They just provide a list of blocking rules to Safari. So that's actually a feature, not a big.
